language: node_js
node_js:
  - 13
cache:
  - directories:
    - node_modules
# before_script:
#   - npm install
script:
  - npm run test
  - npm run lint
  - npm run build:travis

deploy:
  provider: script
  before_script: chmod +x scripts/docker-deploy.sh
  script: bash scripts/docker-deploy.sh
  on:
    branch: master
