language: node_js
node_js:
  - 13
cache:
  - directories:
    - frontend/node_modules
    - backend/node_modules
before_script: chmod +x scripts/build.sh
script: scripts/build.sh

deploy:
  provider: script
  before_script: chmod +x scripts/docker-deploy.sh
  script: bash scripts/docker-deploy.sh
  on:
    branch: master
