version: '3'

services:
  blog_api:
    container_name: strapi
    image: blog.andkra.eu.backend
    build:
      context: ..\.\backend\
      dockerfile: Dockerfile
    env_file:
      - strapi.staging.env
    ports:
      - 1337:1337
    depends_on:
      - db
  blog_app:
    container_name: web
    image: blog.andkra.eu.frontend
    build:
      context: ..\.\frontend\
      dockerfile: Dockerfile
    ports:
      - 2000:80
  db:
    container_name: mysql
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - db.staging.env
    volumes:
      - ./.tmp/db:/var/lib/mysql
    # ports:
    #   - 3306:3306
    # expose:
    #   - "3306"
  # mongo:
  #   image: mongo
  #   container_name: mongoexample
  #   restart: unless-stopped
  #   env_file: db.staging.env
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   networks:
  #     - strapi-app-network
  #   volumes:
  #     - ./.tmp/db:/var/lib/mysql
  #   ports:
  #     - "27017:27017"
networks:  
  strapi-app-network:
    driver: bridge